# Generated by Django 5.0.2 on 2024-05-10 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedCriminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(default='criminal_photos/', upload_to='criminal_photos/')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('criminal_offenses', models.TextField()),
                ('last_known_location', models.CharField(max_length=100)),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_information', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
